### ISSUE TITLE
Batched mutations

### ISSUE THREAD

**Issue by jeroenvisser101** [jaydenseric/graphql-multipart-request-spec#2]
Hi @jaydenseric,

I'm looking to implement this spec into Absinthe's upload handling. I'm just confused by the following:

```json
{
  "1": [
    "0.variables.image",
    "variables.images.0"
  ],
  "2": [
    "variables.images.1"
  ],
  "3": [
    "variables.images.2"
  ]
}
```

Either there's something else going on, or some of these mappings don't have the operation index prefixed in their key. I think it should be like this instead:

```json
{
  "1": [
    "0.variables.image",
    "1.variables.images.0"
  ],
  "2": [
    "1.variables.images.1"
  ],
  "3": [
    "1.variables.images.2"
  ]
}
```

Can you let me know what is the correct way? Thanks for all your work on the client, server and this spec 👍

**Comment by jaydenseric** [comment]
Yes, you're right! Thats a nasty typo 😅

**Comment by jeroenvisser101** [comment]
Not a problem, you want me to submit a PR for it?

**Comment by jaydenseric** [comment]
Yes please!

**Comment by jeroenvisser101** [comment]
@jaydenseric it's in, #3, also, thanks for the super quick response!
