### ISSUE TITLE
Could not find a valid map, be sure to conform to GraphQL multipart request specification

### ISSUE THREAD

**Issue by Joshuaj2804** [jaydenseric/graphql-multipart-request-spec#38]
![image](https://user-images.githubusercontent.com/38155799/92433611-2be2d900-f1d0-11ea-9317-167b634450cd.png)

I have been dealing with this error and have no idea why or where I'm going wrong, I'm sorry if the problem is obvious, a newbie here.

Laravel Lighthouse backend with Apollo Android frontend, the Upload scalar has already been added to the schema

**Comment by jaydenseric** [comment]
This repo is about the GraphQL multipart request specific itself and is not really the right place to ask for help with a particular stack. I hope you solve your problem though! I suggest double checking your requests conform to the spec, you can learn about the structure of a GraphQL multipart request here: 

https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure
